### ISSUE TITLE
about how to create fbwq_full

### ISSUE THREAD

**Issue by zhenjia2017** [malllabiisc/EmbedKGQA#118]
May I know when creating fbqa_full, how to deal with cvt facts?

**Comment by apoorvumang** [comment]
We used the same strategy as used by Pullnet - get all facts within 2-hop of entities in the train/test set. We used the official freebase dump in rdf triples format.

However this also had a lot of facts, so we then restricted it such that we only maintain facts where at least one of subject or object was an entity in the train/test set. This probably was not the best thing to do since this involved 'looking into' the test set since we looked at test answer entities, but this is what we did.

**Comment by apoorvumang** [comment]
This is from Pullnet paper
![image](https://user-images.githubusercontent.com/1957903/156128287-d63c1485-f6c2-4045-b674-f1232ccd68dd.png)

**Comment by zhenjia2017** [comment]
Thanks a lot. Is it correct that cvts are 2-hop facts as the intermediate entity is an object in a triple?

**Comment by apoorvumang** [comment]
Yes

**Comment by apoorvumang** [comment]
@zhenjia2017 btw could you also take a look at this? thanks :) https://github.com/zhenjia2017/EXAQT/issues/2

**Comment by zhenjia2017** [comment]
I am trying to run EmbedKGQA on TimeQuestions :)
