### ISSUE TITLE
question about 3-hop on full KG

### ISSUE THREAD

**Issue by xjtusedy** [malllabiisc/EmbedKGQA#15]
I have run the LSTM code for 3-hop on full KG  settings, but I got a 0.7271963009667928 score. Do I need to change some parameters when I run the code for 3-hop?
Thanks!

**Comment by apoorvumang** [comment]
You are right, we get about ~0.75 with the best hyperparameters but without relation scoring. In 3-hop setting, since the paths are too long, relation scoring is needed to get good performance.

I will be adding the relation scoring soon, I apologize for the delay. Please keep track of the 'relation scoring' issue for this resolution.

**Comment by ToneLi** [comment]
> I have run the LSTM code for 3-hop on full KG settings, but I got a 0.7271963009667928 score. Do I need to change some parameters when I run the code for 3-hop?
> Thanks!
Dear Sir or Madam, can you share your command in metaQA-hop3-full kg, my result in hop3 is 0.48, it's too low.
