### ISSUE TITLE
do_batch_norm in webQSP

### ISSUE THREAD

**Issue by Wangyinquan** [malllabiisc/EmbedKGQA#19]
Batch norm greatly improved training speed for MetaQA. Could you explain why you set do_batch_norm to 0 for WebQSP (lead to more training epoches and patience)? What if we set it to 1? And how much can RelScore improve the results?

**Comment by Wangyinquan** [comment]
Didn't you use batch norm in KGE of WebQSP either?

**Comment by apoorvumang** [comment]
> Batch norm greatly improved training speed for MetaQA. Could you explain why you set do_batch_norm to 0 for WebQSP (lead to more training epoches and patience)? What if we set it to 1? And how much can RelScore improve the results?

For WebQSP we used the KGE training implementation of https://github.com/uma-pi1/kge rather than our own implementation derived from https://github.com/ibalazevic/TuckER. This is because they have optimized their code for large KGs. Their implementation does not used batch norm, and we found through experimentation that training embeddings without batch norm but question embedding with batch norm doesn't yield good results: either do both or none. So we did not use batch norm in WebQSP.

The improvement resulting from RelScore can be found in Table 5 of our paper.

> Didn't you use batch norm in KGE of WebQSP either?

No, since we used a different KGE implementation (as described above) which doesn't do batch norm.
