### ISSUE TITLE
how to run it?

### ISSUE THREAD

**Issue by lbda1** [malllabiisc/EmbedKGQA#5]
how to run knowledge graph embedding?
how to run KBQA model?

**Comment by HTMLgtMK** [comment]
Knowledge graph embedding: 
1. Download dataset from [KnowledgeGraphEmbedding.git](https://github.com/DeepGraphLearning/KnowledgeGraphEmbedding.git). This project contain almost dataset we need for KGE.
2. Enter directory `train_embeddings`, activate python3 env. run command with some arguments in shell:
```shell
python3 main.py \
--dataset FB15k \
--model Rotat3 \
--cuda True
```
**note** : create directory `kg_embeddings` in EmbedKBQA before trainning.


KBQA: 
1. Download [RoBERTa](https://github.com/pytorch/fairseq/tree/master/examples/roberta)  into `./KGQA`, in case of long downloading cost.
2. Download `MetaQA` dataset, and `WebQuestionSP` dataset.
3. modify some directory in `./KGQA/main.py`, specify dataset path.
4. run `./KGQA/main.py`. 
BTW, I am not run this command success yet. Since I cost lots of time in downloading RoBERTa.

**Comment by apoorvumang** [comment]
Hi, thanks for your comments @HTMLgtMK . Some of the instructions you listed might be very useful!
The complete instructions/dataset are yet to be posted. Unfortunately I'm busy with some stuff on my end which is causing this delay. Practically, please expect this to take another week or two to get a properly documented solution for reproducing the results stated in our paper.

The problem is that the current working code/data is not organized properly and needs a bit of refactoring to make it run easily on other machines. _The currently uploaded code, however, is the core of it_.

I hope this is ok. In any case, if this delay seems unjustified, please do let me know and I'll see what I can do.
I'll be keeping this issue pinned in case anyone else also wants to comment on this.
Thanks!

**Comment by apoorvumang** [comment]
Added instructions in the README and updated the code, please check @lbda1
