### ISSUE TITLE
Waiting for cleaned up code

### ISSUE THREAD

**Issue by Wangyinquan** [malllabiisc/EmbedKGQA#9]
When do you plan to update the code?
Hope to see it soon.

**Comment by apoorvumang** [comment]
I have added the code (Aug 5 Indian time :) ). Please let me know of any issues you have in running it. You can experiment with the default hyperparameters if you want, they should work fine. Since the publishing of paper we have made some improvements and I will be sharing the best performing hyperparameters.

I will be adding instructions for running on WebQuestionsSP also, please give me a couple days.

**Comment by Wangyinquan** [comment]
Thanks for updating!
There are some issues about the datasets
It seems you didn't use the original copy of MetaQA kb.txt which has 134.7k triples, yours has 133.5k triples for training and 4k valid, 4k test.
 133.5+4+4!=134.7  
Also it looks like qa_train_2/3hop.txt have some artifical triples added as questions.
Could you explain how you get the datasets?

ps. It seems that pretrained_model.zip is not uploaded.

**Comment by apoorvumang** [comment]
We removed duplicate triples that's why it's 133.5k. Valid and test includes triples from the train dataset - this is necessary if we want to use the full KG. For half KG this is not the case.

For qa_train we added the KB triples as artificial questions. So (h,r,t) became (topic entity, question, answer). The answers were grouped if same h,r had multiple t. This was done so that the model doesn't 'forget' the embeddings, and it's fair since we are using training data only, which is the kb

**Comment by apoorvumang** [comment]
Also I have added pretrained_models.zip now. Seems like I uploaded it to the wrong folder.

**Comment by apoorvumang** [comment]
@Wangyinquan Please download the updated data.zip as well, a couple files were missing.

**Comment by Wangyinquan** [comment]
So added questions are triples and reversed triples in kb and behave as questions here, i.e. QA scoring function use their representations from RoBERTa instead of KGE, right?

**Comment by apoorvumang** [comment]
Yes, the relation names such as 'directed_by' are used by RoBERTa (or BiLSTM), while the entity embeddings are from the pretrained complex embeddings.

Btw the BiLSTM is a simpler model than RoBERTa and we are using it for MetaQA to show that knowledge from RoBERTa is not needed to answer questions for MetaQA.

**Comment by Wangyinquan** [comment]
Get it, thanks a lot!

**Comment by apoorvumang** [comment]
@Wangyinquan I'm marking this issue as resolved. It would be really nice and helpful to others if you could create a new issue each for subsequent problems - then if someone faces the same problem they can easily search it in issues.
